### ISSUE TITLE
Current version NOT work! Even fixed certbot_opts

### ISSUE THREAD

**Issue by SomeOne55468** [zerossl/zerossl-bot#18]
**_zerossl-bot certonly --standalone -d 1.2.3.4 -m anton@example.com_**
Sat Nov  6 21:23:08 CET 2021 **Calling: certbot certonly --standalone -d 1.2.3.4 -m anton@example.com --eab-kid EDITED --eab-hmac-key EDITED --server https://acme.zerossl.com/v2/DV90/**
Requested name 1.2.3.4 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare IP address.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/tmpeafum1dq/log or re-run Certbot with -v for more details.

**Comment by Blackbam** [comment]
@SomeOne55468 Shall be fixed?
