### ISSUE TITLE
504 timeouts

### ISSUE THREAD

**Issue by nikrozman21** [zerossl/zerossl-bot#19]
Hello,

I've been getting 504 gateway timeouts for the last couple of days. I'm 100% certain it's not my server(s) at fault.
Is there any word why it's been going down so much lately? Looking at the status page, it's been having issues for multiple days now!

Here's a short log:
```
$curl https://acme.zerossl.com/v2/DV90
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
```

**Comment by nikrozman21** [comment]
![image](https://user-images.githubusercontent.com/20975185/145248721-8cad5ab1-ebe7-4f60-82f6-45eb7a6b6915.png)

**Comment by Blackbam** [comment]
@nikrozman21 There have been operations issues with scaling the ZeroSSL services, this should be fixed for now. It is not your servers fault. The team is working on making all services stable again.

**Comment by nikrozman21** [comment]
> @nikrozman21 There have been operations issues with scaling the ZeroSSL services, this should be fixed for now. It is not your servers fault. The team is working on making all services stable again.


Thank you for the info, but the issue still persists.

**Comment by Lusitaniae** [comment]
> but the issue still persists.

x2

**Comment by Blackbam** [comment]
> > but the issue still persists.
> 
> x2

There was a temporary downtime today, should be solved since some hours.

**Comment by gitrequests** [comment]
New certificates again impossible to get? Error: acme.errors.TimeoutError 3 days in a row.

**Comment by Lusitaniae** [comment]
Don't have numbers at hand but probably get it dozens of times per week throughout months

But I'm not currently measuring nor retain historical data at the moment

**Comment by gitrequests** [comment]
Renewing certificates works correctly, but getting a new one is impossible.

**Comment by Blackbam** [comment]
Some insights for you: There have been problems with heavily increasing demands. Just yesterday the first part of significant scaling measures have been deployed in order to address ACME issues. Could you re-evaluate and tell if things work better now? 

Temporary downtimes - including 504 - can not always be avoided, there are efforts to improve reliability.

**Comment by gitrequests** [comment]
Last 6 attempts within an hour
![Screenshot from 2022-03-09 13-56-24](https://user-images.githubusercontent.com/12627650/157429217-aa06f5b9-0c69-4b18-bdfd-7a9e2484db5c.png)

**Comment by Blackbam** [comment]
Due to significant improvements in stability this issue is closed. Please open a new issue in case you experience this issue for a longer timespan. Please note that especially in the weekend there are maintenance windows which can cause downtimes temporarily.
