### ISSUE TITLE
Install script pulling the wrong bot script

### ISSUE THREAD

**Issue by Leviosar** [zerossl/zerossl-bot#21]
Hey folks, even with the args bug being fixed with #15, the [get-zerosslbot.sh](https://github.com/zerossl/zerossl-bot/blob/master/get-zerosslbot.sh) script downloads the file at https://zerossl.com/zerossl-bot.sh, which is outdated. So when using the installer, we get "pre" #15 bot that doesn't work at all. Could you please update the file at https://zerossl.com/zerossl-bot.sh to the new one?

**Comment by tiny-dancer** [comment]
Temporary workaround: 

```
export ZEROSSLBOT_SCRIPT_LOCATION=https://raw.githubusercontent.com/zerossl/zerossl-bot/master/zerossl-bot.sh && bash <(curl -s https://zerossl.com/get-zerosslbot.sh)
```

**Comment by Blackbam** [comment]
@Leviosar Is this problem solved?

**Comment by jeremythehunt** [comment]
This still isn't fixed. After banging my head against my desk for a bit wondering why things weren't working, I realized that https://zerossl.com/zerossl-bot.sh is still the old broken version of the script compared to the latest in this repo. Grabbed the version from this repo that was fixed a few months ago and all is good.

**Comment by Blackbam** [comment]
@jeremythehunt Fixed.
