### ISSUE TITLE
I tried to use this script but it errors.. 

### ISSUE THREAD

**Issue by cconstab** [zerossl/zerossl-bot#3]
The ARGS variable on the last line I am sure is the wrong ARG ???

Surely this should be certbot ${CERTBOT_ARGS[@]}  ??

The python clever stuff just errors for me with any version of Python..

I just by passed everything here and just added the hmac/kid/server vars to certbot which worked fine... Which sorta defeats the point of the script :-)

I did BTW upgrade the certbot install etc so those dependencies were dealt with..

I may well be missing something...

cconstab@orac:~$ sudo certbot-zerossl certonly --standalone -m colin@mydomain.come home.mydomain.com
[sudo] password for cconstab:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
cconstab@orac:~$

**Comment by Gowee** [comment]
I was even wondering whether there is something wrong with myself.

But later I realize THE SCRIPT DOES NOT WORK AT ALL.

It is so ridiculous that the "official" script gets shown on https://zerossl.com/features/acme/ as a feature.

Is ZeroSSL the whole project/company still under maintained/operated?

**Comment by StefanMarkmann** [comment]
To be fair, with that fix it worked almost always. Sometimes i got a 302 or something, but that can be handled within a loop and is internet-normal. 

Seeing them as only viable option against letsencrypt without rate-limit for just 10 bucks, with such a presence and board, makes me wonder, why i fix their scripts for free. They are not even pulling it or maintaining any presence here. But it's on the home-page as major product. It's even the only non-US based CA with such functionality and is thereby relevant as f... This should be in Gaia-X or something.

Indeed ridiculous.

**Comment by Gowee** [comment]
Someone told me EAB keys used to authenticate with acme server do not appear to change at all. So just note down those keys for subsequent usage with certbot and forget this script.
