### ISSUE TITLE
inconsistent handling of --zerossl-email=... vs --zerossl-email ...

### ISSUE THREAD

**Issue by mralusw** [zerossl/zerossl-bot#30]
I've opened PR #29 . While looking at the arg parser, I've noticed that `--zerossl-email=$EML` just puts the email into the `curl --data` parameter, the output of which gets parsed by `parse_eab_credentials()`; meanwhile, `--zerossl-email $EML` (with a separate arg) does that as well, but *also* adds `-m $EML` to `certbot`'s args.

If intended, it seems quite confusing and should be documented. I'm guessing it was an oversight, though?

**Comment by Blackbam** [comment]
@mralusw Can you explain the consequences of adding the E-Mail to the certbot args? Does it do any harm? Guess it was an oversight though, too.

**Comment by mralusw** [comment]
Well, can someone explain what adding `-m $EML` to certbot's args does? This is already what happens for `zerossl-bot.sh --zerossl-email $EML`. I *think* that `certbot -m $EML` is so that the CA can send e-mail reminders when the certificate is about to expire. I don't know if `zerossl` needs this parameter, as the account is presumably already registered.

Either `-m $EML` should be added to `certbot`'s args in both usages, or in neither.

**Comment by norbertosus** [comment]
https://github.com/zerossl/zerossl-bot/issues/30#issue-1514264037
