### ISSUE TITLE
zerossl-bot and non standard ports

### ISSUE THREAD

**Issue by digitall-it** [zerossl/zerossl-bot#32]
Can I use zerossl-bot to automate the renewal of a certificate on a web server that is running on the non standard port 30443 ?

**Comment by Blackbam** [comment]
@digitall-it Zerossl-Bot is essentially a wrapper around Certbot, you can check the Certbot community if they have options for that. Afaik for the domain validation you need port 80 / 443.

**Comment by Blackbam** [comment]
Closed as no further reaction.
