### ISSUE TITLE
zerossl-bot.sh wrapper is using the wrong variable for ARGS

### ISSUE THREAD

**Issue by bitroniq** [zerossl/zerossl-bot#33]
# Problem statement

`zerossl-bot.sh` wrapper is using the wrong variable for ARGS

## Steps to reproduce

1. Install zerosll wrapper `root@vmubuntu2004srv:~# bash <(curl -s https://zerossl.com/get-zerosslbot.sh)`
2. Get API key from https://app.zerossl.com/developer
3. Setup DNS on own domain pointing to your IP
4. Setup Apache site using mydomain.com
    ```
    root@vmubuntu2004srv:~# cat /etc/apache2/sites-available/mydomain.com.conf
    <VirtualHost *:80>
            ServerName mydomain.com
            DocumentRoot /var/www/html
    </VirtualHost>
    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
    ```
6. Open port `80` and `443`
7. Make sure you can visit http://mydomain.com
8. Run zerossl cerbot wrapper
    ```
    root@vmubuntu2004srv:~# zerossl-bot --apache -d mydomain.com -m admin@mydomain.com --zerossl-api-key 123123123123123123123123123123
    ```

## Visible results

The certificate is issued by Let's Encrypt instead of ZeroSSL

## Expected results

The certificate should be issues by ZeroSSL

## Proposed solution

The last line of `zerossl-bot.sh` is wrong - is using `ARGS` instead of `CERTBOT_ARGS`

## Working script

```
#!/bin/bash

CERTBOT_ARGS=()

function parse_eab_credentials()
{
    PYTHONIOENCODING=utf8
    ZEROSSL_EAB_KID=$(echo $1 | python -c "import sys, json; print(json.load(sys.stdin)['eab_kid'])")
    ZEROSSL_EAB_HMAC_KEY=$(echo $1 | python -c "import sys, json; print(json.load(sys.stdin)['eab_hmac_key'])")
    CERTBOT_ARGS+=(--eab-kid "$ZEROSSL_EAB_KID" --eab-hmac-key "$ZEROSSL_EAB_HMAC_KEY" --server "https://acme.zerossl.com/v2/DV90")
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --zerossl-api-key=*)
            ZEROSSL_API_KEY="${1:18}"
        ;;
        --zerossl-api-key|-z)
           ZEROSSL_API_KEY="${2}"
           shift
        ;;
        --zerossl-email=*)
            ZEROSSL_EMAIL="${1:16}"
        ;;
        --email|--zerossl-email|-m)
           ZEROSSL_EMAIL="${2}"
           CERTBOT_ARGS+=(-m "${2}")
           shift
        ;;
        *) CERTBOT_ARGS+=($1) ;;
    esac
    shift
done

if [[ -n $ZEROSSL_API_KEY ]]; then
    parse_eab_credentials $(curl -s -X POST "https://api.zerossl.com/acme/eab-credentials?access_key=$ZEROSSL_API_KEY")
elif [[ -n $ZEROSSL_EMAIL ]]; then
    parse_eab_credentials $(curl -s https://api.zerossl.com/acme/eab-credentials-email --data "email=$ZEROSSL_EMAIL")
fi

echo ${CERTBOT_ARGS[@]}
certbot ${CERTBOT_ARGS[@]}
```

**Comment by Blackbam** [comment]
@bitroniq Thank you for your report! Can you confirm this MR would fix the problem? 
https://github.com/zerossl/zerossl-bot/pull/34/files

**Comment by bitroniq** [comment]
> @bitroniq Thank you for your report! Can you confirm this MR would fix the problem? https://github.com/zerossl/zerossl-bot/pull/34/files

PR looks good to me - this should solve the problems

Here is my review with the comment:
https://github.com/zerossl/zerossl-bot/pull/34#pullrequestreview-1374835219

The thing is though that the official downloader 
- https://zerossl.com/get-zerosslbot.sh
Is pulling the file from
- https://zerossl.com/zerossl-bot.sh

And the `https://zerossl.com/zerossl-bot.sh` is broken (wrong last line - `ARGS` instead of `CERTBOT_ARGS`.

**Comment by Blackbam** [comment]
@bitroniq Changed get-zerosslbot.sh to always use the latest version from Github master. Does this fix the problem? The version on zerossl.com is outdated.

**Comment by bitroniq** [comment]
@Blackbam that will fix the problem. Thx!

BTW. Will you update the script here https://zerossl.com/get-zerosslbot.sh as well to always get latest from github?

**Comment by Blackbam** [comment]
@bitroniq Fixed ✌

**Comment by bitroniq** [comment]
> @bitroniq Fixed ✌

Great! I see and tested it, everything works as expected now.
Thank you!
