### ISSUE TITLE
How to get 1 year cert (365 days) with ACME? 

### ISSUE THREAD

**Issue by TiloGit** [zerossl/zerossl-bot#41]
Hi, 

we want to get 1 year certs via ACME. We upgrade our plan to basic (3 x1year cert included) but can't figure out how to get a 1year valid cert.

Please advise.

**Comment by TiloGit** [comment]
ZeroSSL support stated:

> Regarding ACME - it's currently limited to 90-day certificates. 1-year certificates cannot be issued via ACME.

Would be great to have that function.

**Comment by Blackbam** [comment]
@TiloGit This will not be implemented because the ACME service of ZeroSSL is free while 1-Year certificates are a premium product (just like with any SSL vendor). If you need automation with 1-Year certificates here is a sample application: https://github.com/zerossl/cli-client .
