### ISSUE TITLE
Installation Dependencies

### ISSUE THREAD

**Issue by miqrogroove** [zerossl/zerossl-bot#43]
https://github.com/zerossl/zerossl-bot/blob/705969881fad29497feb376a0e198fbae8d98746/README.md?plain=1#L10

https://github.com/zerossl/zerossl-bot/blob/705969881fad29497feb376a0e198fbae8d98746/zerossl-bot.sh#L16

If I'm reading these correctly, the instructions should specify python is required too.

**Comment by Blackbam** [comment]
@miqrogroove Have added the missing information to the installation instructions.
