### ISSUE TITLE
certbot-zerossl is using letsencrypt server

### ISSUE THREAD

**Issue by alexmck** [zerossl/zerossl-bot#5]
Hello,

I have installed certbot-zerossl, but I am having trouble getting it to use zerossl's ACME server.

I am running `sudo certbot-zerossl --nginx --agree-tos --non-interactive --redirect -d subdomain.example.com -d cname.example.com --zerossl-api-key MY_ZEROSSL_API_KEY`

The process also appears to be taking me through the interactive prompts, and hitting Let's Encrypt's ACME servers. Have I missed something obvious?

**Comment by sulliops** [comment]
Could you paste the output when you run the above command? certbot-zerossl is just a wrapper, not a rewrite of certbot; as such, you'll still see the same prompts and language that you'd see in certbot using LE, but it'll be using ZeroSSL's ACME server in the background.

**Comment by Crashdummyy** [comment]
Any news on this ?? 
I am facing the same problems...

**Comment by Crashdummyy** [comment]
PR !8 appears to solve this issue...

**Comment by neobie** [comment]
Facing same problem today. How to fix ?

**Comment by Blackbam** [comment]
Shall be fixed.
