### ISSUE TITLE
Will zerossl-bot client be supported in the future without snap?

### ISSUE THREAD

**Issue by n3storm** [zerossl/zerossl-bot#9]
One of the reasons we are willing to subscribe to zerossl is cerbot-auto not being supported because they are moving to snap but I am reading issues and just installed zerossl-bot and get this message:

Your system is not supported by certbot-auto anymore.
certbot-auto and its Certbot installation will no longer receive updates.
You will not receive any bug fixes including those fixing server compatibility
or security problems.

**Comment by osirisinferi** [comment]
"zerossl-bot" is NOT an ACME client by itself. It's just a very simple wrapper script with some ZeroSSL specific stuff, but it just runs Certbot. There are ways to install Certbot without snap, such as using `pip`. No need to switch to ZeroSSL.
